/*
 * jQuery "JustSlide" content slider plug-in 0.4 OUTDATED....
 *
 * http://blog.justprofessionals.com/just-professionals/just-slide-jquery-content-slider/
 * Copyright (c) 2010 Jeremy Woertink
 *
 * Dual licensed under the MIT and GPL licenses:
 *   http://www.opensource.org/licenses/mit-license.php
 *   http://www.gnu.org/licenses/gpl.html
 */
eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('(3($){$.16($.17,{18:3(){5 c=19;5 d=1a[0]||{};c.C=d[\'C\']||2;c.K=d[\'K\']||1;c.w=d[\'w\']||\'L\';c.D=d[\'D\']||s;c.M=($(c).4().u>1)?1b:s;c.E=3(a){6(\'N\'1c O)O.N.E(a)}c.v=3(a){6(a!=P){$(a).Q(\'R\',3(){l();9 s})}q{l()}}c.t=3(a){6(a!=P){$(a).Q(\'R\',3(){k();9 s})}q{k()}}c.S=3(){m()}6(c.M){5 f=$(c).4().u;$(c).4().7({\'1d\':\'p\',\'F\':\'1e\',\'z-T\':2,\'G\':0});3 U(a,b){6(a.r<b.r)9-1;6(a.r==b.r)9 0;6(a.r>b.r)9 1}5 g=3(){5 a=0;5 b=$(c).4().1f(U)[$(c).4().u-1];a+=$(b).r();a+=8($(b).7(\'x-G\'),10);a+=8($(b).7(\'x-V\'),10);a+=8($(b).7(\'y-G\'),10);a+=8($(b).7(\'y-V\'),10);9 a}5 h=3(){5 a=0;a+=$(c).4().W();a+=8($(c).4().7(\'x-p\'),10);a+=8($(c).4().7(\'x-X\'),10);a+=8($(c).4().7(\'y-p\'),10);a+=8($(c).4().7(\'y-X\'),10);9 a}$(c).7({\'F\':\'1g\',\'1h\':\'1i\',\'1j-1k\':\'1l\',\'z-T\':\'1\',\'W\':((h()*c.C)+\'Y\'),\'r\':(g()+\'Y\')});5 j=0;$(c).4().1m(3(i,e){$(e).7(\'p\',j);j+=h()});5 k=3(){6(o()){$(c).4().H({p:\'-=\'+I.J(8(h()),10)},c.w)}q{9 s}}5 l=3(){6(n()){$(c).4().H({p:\'+=\'+I.J(8(h()),10)},c.w)}q{9 s}}5 m=3(){5 a=$(c).4(\':1n\').F().p;$(c).4().H({p:\'+=\'+I.J(a)},\'L\')}5 n=3(){9(8($(c).4(\':Z(0)\').7(\'p\'),10)+h()<=0)}5 o=3(){9(8($(c).4(\':Z(\'+(f-1)+\')\').7(\'p\'),10)-h()>=0)}6($(d[\'t\']).u>0){c.t(d[\'t\'])}q{$(c).11(\'<a 12="#" 13="14" A="\'+c.B+\'">1o &1p;</a>\');c.t(\'.14[A^=\'+c.B+\']\')}6($(d[\'v\']).u>0){c.v(d[\'v\'])}q{$(c).11(\'<a 12="#" 13="15" A="\'+c.B+\'">&1q; 1r</a>\');c.v(\'.15[A^=\'+c.B+\']\')}6(c.D){1s(3(){6(o()){c.t()}q{c.S()}},1t)}}q{c.E(\'1u 1v 1w 1x. 1y 1z 1A 1B 1C.\')}}})})(1D);',62,102,'|||function|children|var|if|css|parseInt|return||||||||||||||||left|else|height|false|next|length|prev|speed|margin|padding||rel|selector|display|autoSlide|log|position|top|animate|Math|abs|slide|slow|enabled|console|window|null|live|click|reset|index|spaceship|bottom|width|right|px|eq||after|href|class|nextSlide|prevSlide|extend|fn|justslide|this|arguments|true|in|float|absolute|sort|relative|overflow|hidden|list|style|none|each|first|Next|rarr|larr|Previous|setInterval|6000|Could|not|activate|slider|Try|adding|more|child|elements|jQuery'.split('|'),0,{}))